apiVersion: v1
data:
  .dockerconfigjson: |
    ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJiMmRzYjJzNlFUVXJhVFJQVFhoMVlVNXdVbGRLYVRoQ05UUlFRVlV3Y2poc2MwMUlhVVJ4WkRSNmMyOUxZUzl5VVZoVmNUWmxWRTgyWlhSNEswWXJTVkYzWTFOUlRnPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: multicloud-operators
  namespace: multicloud-operators
type: kubernetes.io/dockerconfigjson
